### ISSUE TITLE
Error：请确认调用规则是否正确

### ISSUE THREAD

**Issue by badboycxcc** [WPeace-HcH/SysNR-FuncFinder#1]
![飞书20221207-161332](https://user-images.githubusercontent.com/72059221/206124376-5dc3d4c1-2663-405b-b3dc-c15691d0cebe.jpg)

**Comment by badboycxcc** [comment]
换成Mips架构后

Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] 
IDAPython v7.4.0 final (serial 0) (c) The IDAPython Team <[idapython@googlegroups.com](mailto:idapython@googlegroups.com)>
--------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/x/Desktop/IDA_Pro_v7.5_Portable/plugins/SysNR-FuncFinder_WPeace.py", line 124, in activate
    self.plugin.patcher()
  File "C:/Users/x/Desktop/IDA_Pro_v7.5_Portable/plugins/SysNR-FuncFinder_WPeace.py", line 47, in patcher
    LinuxFuncFinder_Mips32.main()
  File "C:\Users\x\Desktop\IDA_Pro_v7.5_Portable\plugins\LffPlugDir_WPeace\LinuxFuncFinder_Mips32.py", line 453, in main
    ReName();
    ^^^^^^^^
  File "C:\Users\x\Desktop\IDA_Pro_v7.5_Portable\plugins\LffPlugDir_WPeace\LinuxFuncFinder_Mips32.py", line 438, in ReName
    CallNumber = int(opString, 16);
                 ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: 'C($v1)'

**Comment by WPeace-HcH** [comment]
哈喽，如果方便的话可以提供一下对应样本的MD5吗？

**Comment by badboycxcc** [comment]
使用最新的还是上述错误，样本你留个邮箱我发给你吧。

**Comment by WPeace-HcH** [comment]
hackinwpeace@gmail.com

**Comment by WPeace-HcH** [comment]
新版本已解决，尝试使用v1.4版本进行解析即可。
如果还有问题的话可以邮件联系我哈 : )

**Comment by badboycxcc** [comment]
ok，明天去测试。

**Comment by badboycxcc** [comment]
初步测试一切正常
