### ISSUE TITLE
Got the error of "list index out of range"

### ISSUE THREAD

**Issue by fantasyGit2023** [WPeace-HcH/SysNR-FuncFinder#3]
Hi, thank u for this plugin, when i tried it, i got an error,
SysNR-FuncFinder v1.5 start running...
LinuxFuncFinder_x64 finished！总共重命名0个函数
Traceback (most recent call last):
  File "D:/IDA_Pro_7.7/plugins/SysNR-FuncFinder_WPeace.py", line 138, in activate
    self.plugin.patcher()
  File "D:/IDA_Pro_7.7/plugins/SysNR-FuncFinder_WPeace.py", line 53, in patcher
    LinuxFuncFinder_x64.main()
  File "D:\IDA_Pro_7.7\plugins\LffPlugDir_WPeace\LinuxFuncFinder_x64.py", line 396, in main
    RenameStartFunc()
  File "D:\IDA_Pro_7.7\plugins\LffPlugDir_WPeace\LinuxFuncFinder_x64.py", line 387, in RenameStartFunc
    GetMainFunc(func)
  File "D:\IDA_Pro_7.7\plugins\LffPlugDir_WPeace\LinuxFuncFinder_x64.py", line 378, in GetMainFunc
    mainAddr = int(mainOP.split("sub_")[1], 16)
IndexError: list index out of range

**Comment by WPeace-HcH** [comment]
Hi. Could you please provide me the md5 that have this error? Or you can send the sample to my Gmail :)

**Comment by WPeace-HcH** [comment]
I have found and fixed the error, please update to v1.6 :)

**Comment by fantasyGit2023** [comment]
Many thx! it is worked :D
