### ISSUE TITLE
2.1 版本分析mips错误

### ISSUE THREAD

**Issue by badboycxcc** [WPeace-HcH/SysNR-FuncFinder#4]
```
SysNR-FuncFinder v2.1 start running...
_WPe_mmap
_WPe_clone
Traceback (most recent call last):
  File "C:/Users/IDA/Desktop/IDA_Pro_7.7/plugins/SysNR-FuncFinder.py", line 142, in activate
    self.plugin.patcher()
  File "C:/Users/IDA/Desktop/IDA_Pro_7.7/plugins/SysNR-FuncFinder.py", line 60, in patcher
    LinuxFuncFinder_Mips32.main()
  File "C:\Users\IDA\Desktop\IDA_Pro_7.7\plugins\LffPlugDir_WPeace\LinuxFuncFinder_Mips32.py", line 577, in main
    ReName_DirectCall()
  File "C:\Users\IDA\Desktop\IDA_Pro_7.7\plugins\LffPlugDir_WPeace\LinuxFuncFinder_Mips32.py", line 457, in ReName_DirectCall
    callNumber = int(opString, 16)
ValueError: invalid literal for int() with base 16: '40+var_24($sp)'
```

**Comment by WPeace-HcH** [comment]
插件切割调用号时出错了，方便的话可以把对应样本通过邮箱发给我进行调试修改。: )

**Comment by badboycxcc** [comment]
请查收

WPeace-HcH ***@***.***> 于2023年5月25日周四 11:15写道：

**Comment by WPeace-HcH** [comment]
你好，已修复 下载最新版本即可。: )
